package com.oracle.web.bean;

public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bid
     *
     * @mbg.generated Wed May 08 12:12:17 GMT+08:00 2019
     */
    private Integer bid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bname
     *
     * @mbg.generated Wed May 08 12:12:17 GMT+08:00 2019
     */
    private String bname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bprice
     *
     * @mbg.generated Wed May 08 12:12:17 GMT+08:00 2019
     */
    private String bprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.chubanshe
     *
     * @mbg.generated Wed May 08 12:12:17 GMT+08:00 2019
     */
    private String chubanshe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.zhuangtai
     *
     * @mbg.generated Wed May 08 12:12:17 GMT+08:00 2019
     */
    private String zhuangtai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.jieshuren
     *
     * @mbg.generated Wed May 08 12:12:17 GMT+08:00 2019
     */
    private String jieshuren;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.fid
     *
     * @mbg.generated Wed May 08 12:12:17 GMT+08:00 2019
     */
    private Integer fid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bid
     *
     * @return the value of book.bid
     *
     * @mbg.generated Wed May 08 12:12:17 GMT+08:00 2019
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bid
     *
     * @param bid the value for book.bid
     *
     * @mbg.generated Wed May 08 12:12:17 GMT+08:00 2019
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bname
     *
     * @return the value of book.bname
     *
     * @mbg.generated Wed May 08 12:12:17 GMT+08:00 2019
     */
    public String getBname() {
        return bname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bname
     *
     * @param bname the value for book.bname
     *
     * @mbg.generated Wed May 08 12:12:17 GMT+08:00 2019
     */
    public void setBname(String bname) {
        this.bname = bname == null ? null : bname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bprice
     *
     * @return the value of book.bprice
     *
     * @mbg.generated Wed May 08 12:12:17 GMT+08:00 2019
     */
    public String getBprice() {
        return bprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bprice
     *
     * @param bprice the value for book.bprice
     *
     * @mbg.generated Wed May 08 12:12:17 GMT+08:00 2019
     */
    public void setBprice(String bprice) {
        this.bprice = bprice == null ? null : bprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.chubanshe
     *
     * @return the value of book.chubanshe
     *
     * @mbg.generated Wed May 08 12:12:17 GMT+08:00 2019
     */
    public String getChubanshe() {
        return chubanshe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.chubanshe
     *
     * @param chubanshe the value for book.chubanshe
     *
     * @mbg.generated Wed May 08 12:12:17 GMT+08:00 2019
     */
    public void setChubanshe(String chubanshe) {
        this.chubanshe = chubanshe == null ? null : chubanshe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.zhuangtai
     *
     * @return the value of book.zhuangtai
     *
     * @mbg.generated Wed May 08 12:12:17 GMT+08:00 2019
     */
    public String getZhuangtai() {
        return zhuangtai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.zhuangtai
     *
     * @param zhuangtai the value for book.zhuangtai
     *
     * @mbg.generated Wed May 08 12:12:17 GMT+08:00 2019
     */
    public void setZhuangtai(String zhuangtai) {
        this.zhuangtai = zhuangtai == null ? null : zhuangtai.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.jieshuren
     *
     * @return the value of book.jieshuren
     *
     * @mbg.generated Wed May 08 12:12:17 GMT+08:00 2019
     */
    public String getJieshuren() {
        return jieshuren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.jieshuren
     *
     * @param jieshuren the value for book.jieshuren
     *
     * @mbg.generated Wed May 08 12:12:17 GMT+08:00 2019
     */
    public void setJieshuren(String jieshuren) {
        this.jieshuren = jieshuren == null ? null : jieshuren.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.fid
     *
     * @return the value of book.fid
     *
     * @mbg.generated Wed May 08 12:12:17 GMT+08:00 2019
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.fid
     *
     * @param fid the value for book.fid
     *
     * @mbg.generated Wed May 08 12:12:17 GMT+08:00 2019
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }
}